version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:01"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "deps"
    groups:
      spring:
        patterns:
          - "org.springframework*"
      aws:
        patterns:
          - "software.amazon.awssdk*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"