server:
  port: 8080

logging:
  file:
    name: logs/application.log
  structured:
    format:
      file: logstash

spring:
  application:
    name: case-manager

  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20
        page-parameter: page
        size-parameter: size
        sort-parameter: sort

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:  
              - read:user
              - user:email

app:
  storage:
    provider: s3
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_REGION}
      public-base-url: ${AWS_S3_PUBLIC_BASE_URL}