spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: test
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: h2

app:
  storage:
    provider: none
